apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../base
patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
secretGenerator:
  - name: cloud-app-secret
    behavior: replace
    literals:
      - SPRING_DATASOURCE_USERNAME=cloudapp
      - SPRING_DATASOURCE_PASSWORD=devpassword
      - POSTGRES_USER=cloudapp
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=cloudapp
generatorOptions:
  disableNameSuffixHash: true
