controller:
  service:
    type: LoadBalancer
  ingressClassResource:
    default: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
