apiVersion: v1
kind: Secret
metadata:
  name: cloud-app-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: cloudapp
  SPRING_DATASOURCE_PASSWORD: changeme
  POSTGRES_USER: cloudapp
  POSTGRES_PASSWORD: changeme
  POSTGRES_DB: cloudapp
