apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../base
patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
  - path: postgres-patch.yaml
    target:
      kind: StatefulSet
      name: postgres
secretGenerator:
  - name: cloud-app-secret
    behavior: replace
    envs:
      - .env.remote
generatorOptions:
  disableNameSuffixHash: true
